# 1. read()
f=open("one.txt","r")
data = f.read()
print("File content:", data)
f.close()

# 2. char()
f=open("one.txt","r")
data = f.read(5)
print("First Part:", data)
f.close()

# 3. readline()
f=open("one.txt","r")
line1 = f.readline()
line2 = f.readline() 
line3 = f.readline()
print("Line 1:", line1)
print("Line 2:", line2)
print("Line 3:", line3)
f.close()

# 4. readlines() Read all lines into a list
f=open("one.txt","r")
lines = f.readlines()
print("Lines of lines:",lines)
print("Number of lines:", len(lines))
f.close()

# 5. Strip()
f=open("one.txt","r")
lines = f.readlines()   
print(lines[1].strip())
f.close()